# -*- coding: utf-8 -*-
from typing import Dict, List, Tuple

def _t(q: str, good: str, bad: List[str], rot: int = 1) -> Tuple[str, List[str], int]:
    ops = list(bad[:3])
    while len(ops) < 3:
        ops.append("Actuar sin registro ni responsable")
    pos = rot % 4
    ops.insert(pos, good)
    return (q, ops[:4], pos)

def _p(rows: List[Tuple[str, str, List[str], int]]) -> List[Tuple[str, List[str], int]]:
    return [_t(q, g, b, r) for q, g, b, r in rows]

BANCO_PART: Dict[str, List[Tuple[str, List[str], int]]] = {
    "DIR_MEDICO": _p([
        ("Código en rol desordenado. Control del Director Médico:", "Asignar roles de escena, líder clínico y punto de información", ["Que cada uno improvise con creatividad", "Silencio total sin líder", "Liderazgo al que escribe más rápido"], 1),
        ("Residente comete error de protocolo. Control formativo:", "Corregir, enseñar y registrar si es grave o reiterado", ["Humillar en el canal para que aprenda", "Ignorar para no cortar el RP", "Expulsar del server sin expediente"], 2),
        ("Conflicto OOC entre médicos en escena:", "Sacar el OOC, preservar IC y mediar fuera", ["Dejar el OOC en la escena", "Banear a ambos sin escuchar", "Borrar el canal clínico"], 0),
        ("Médico se niega a cobertura sin motivo de rol:", "Exigir justificación válida y asegurar cobertura alternativa", ["Dejar urgencias descubiertas", "Ban inmediato por falta de compromiso", "Que un visitante cubra sin proceso"], 1),
        ("Documentación mínima de ingreso de RP:", "Motivo, hallazgos relevantes, plan y responsable", ["Solo un emoji", "Omitir si hubo prisa", "Inventar para troll"], 3),
        ("Coordinación con Enfermería en escena crítica:", "Órdenes claras, confirmación y actualización de estado", ["Órdenes contradictorias para probar al equipo", "Solo OOC tóxico", "Asumir que ya saben"], 1),
        ("Relación de control con Docencia:", "Alinear competencias de RP y validar estándares", ["Bloquear certificaciones por ego", "Ignorar la formación", "Que Docencia dicte cada tratamiento"], 2),
        ("Priorización en urgencias de RP:", "Gravedad y riesgo de la escena, no el rango Discord", ["Mejor color de rol", "Siempre orden de llegada", "Quien pide más en el chat"], 0),
        ("Error grave reiterado de un especialista:", "Expediente, límites de práctica de RP y escalado según norma", ["Omitir por ser bueno en otras cosas", "Escarnio público", "Quitar el rol en silencio sin proceso"], 1),
        ("¿Qué NO es control directivo médico?", "Sustituir siempre al médico tratante en cada paciente del server", ["Definir protocolos de escena", "Supervisar calidad del equipo", "Coordinar cobertura crítica"], 2),
        ("Transferencia a otra área. Control de información:", "Estado actual, lo hecho y pendientes explícitos", ["Ya lo ven ellos", "Inventar para acelerar", "Solo un chiste de pasillo"], 1),
        ("Interno pregunta algo básico en plena escena:", "Respuesta breve útil o reasignación sin romper seguridad de escena", ["Ridiculizar en público", "Ignorar por completo", "Quitar el rol al instante"], 0),
        ("Doble liderazgo clínico confuso:", "Nombrar un líder de escena y un canal de órdenes", ["Ambos den órdenes a la vez", "Líder al más agresivo en OOC", "Ninguno por libertad creativa"], 3),
        ("Protocolo clínico de RP dudoso:", "Contrastar con norma del área y unificar criterio", ["Que cada médico invente el suyo", "Imponer tu gusto sin norma", "Ocultar el protocolo al equipo"], 1),
        ("Indicador de control del servicio médico:", "Escenas críticas con roles claros y handoffs completos", ["Solo duración del voice", "Cantidad de muertes PK", "Sin registro porque es RP"], 2),
        ("Queja sobre un médico de tu equipo:", "Escuchar, contrastar hechos y aplicar proceso del área/RRHH", ["Defender a ciegas por lealtad", "Sancionar sin oír a la otra parte", "Publicar la queja en anuncios"], 0),
        ("Cobertura nocturna débil:", "Plan de turnos, responsables y escalado si falla", ["Si alguien aparece bien", "Una persona 24/7 sin relevo", "Plan secreto solo para tu círculo"], 1),
        ("Confidencialidad del paciente de RP:", "Compartir solo con necesidad asistencial de la escena", ["En general para que todos roleen", "Como chisme de staff", "Nunca ni con el equipo tratante"], 2),
        ("Cierre de escena médica compleja:", "Estado final, plan y responsable de seguimiento", ["Desconectarte sin estado", "Trollear al paciente", "Borrar el canal útil"], 1),
        ("Meta de control como Director Médico:", "Calidad y orden del RP clínico del equipo, no protagonismo eterno", ["Solo tu tiempo en escena", "Prohibir residentes", "Ignorar protocolos si hay feeling"], 0),
    ]),
    "DIR_ENFERMERIA": _p([
        ("Varios pacientes. Criterio de prioridad:", "Gravedad y dependencia, no el rango Discord", ["Siempre orden de llegada", "Quien escribe más", "Color del rol del paciente"], 1),
        ("Medicación en RP. Control mínimo:", "Verificar orden, paciente, vía y registro breve", ["Solo color del frasco", "Omitir registro por prisa", "Inventar dosis para acelerar"], 2),
        ("Auxiliar incumple aislamiento:", "Corregir de inmediato, educar y reportar si es grave", ["Reírse sin más", "Ban al instante sin contexto", "Ignorar para no cortar el RP"], 0),
        ("Orden médica confusa:", "Pedir aclaración antes de ejecutar mal", ["Hacer lo contrario a propósito", "Humillar al médico en RP", "Arriesgar al paciente de rol"], 1),
        ("Turno corto de personal:", "Redistribuir tareas críticas y escalar falta de cobertura", ["Abandonar pacientes menos interesantes", "Cerrar el área en silencio", "Dar rol de enfermero a cualquiera"], 3),
        ("Liderazgo en crisis de enfermería:", "Asignar tareas, tiempos y punto de control del equipo", ["Gritos sin roles claros", "Salir de la escena el líder", "Que cada uno haga lo que quiera"], 1),
        ("Confidencialidad del paciente:", "Solo necesidad asistencial del equipo que atiende", ["Publicar en general", "Chisme de descanso", "Nunca ni con el médico"], 2),
        ("Conflicto entre enfermeros en turno:", "Separar, escuchar, mediar y documentar si afecta servicio", ["Pelea en el pasillo de rol", "Ban al más nuevo", "Cerrar el turno completo"], 0),
        ("Formación de auxiliares:", "Impulsarla desde Enfermería con apoyo de Docencia si aplica", ["Solo Seguridad", "Solo si el Owner lo pide", "Nunca porque se aprende solo"], 1),
        ("Entrega de turno. Control mínimo:", "Pendientes, pacientes críticos y riesgos abiertos", ["Ya se ven", "Falsos para quedar bien", "Solo drama OOC"], 2),
        ("Falta material de enfermería:", "Reportar por canal de Logística/área y registrar el faltante", ["Solo memes", "Culpar sin datos", "Nada e improvisar"], 1),
        ("Indicador de control del servicio:", "Cobertura de turnos y escenas con roles de cuidado claros", ["Solo tiempo en voice", "Cantidad de mensajes", "Ignorar si el Director está online"], 0),
        ("Médico da órdenes contradictorias:", "Detener, clarificar con el líder de escena y unificar", ["Elegir la más peligrosa por velocidad", "Insultar en OOC en la escena", "Ejecutar ambas a la vez"], 3),
        ("¿Qué NO es control de Dir. Enfermería?", "Sustituir diagnóstico y liderazgo médico en toda escena por sistema", ["Organizar turnos y estándares", "Supervisar auxiliares y registros", "Coordinar con el equipo médico"], 1),
        ("Paciente agitado en recepción:", "Abordaje calmado según protocolo y aviso a quien corresponda", ["Insultos para imponer respeto", "Ignorar riesgo claro", "Ban al primer grito sin contexto"], 2),
        ("Doble reporte de estado del mismo paciente:", "Unificar fuente de verdad con el equipo tratante", ["Dejar ambas versiones", "Borrar registros útiles", "Inventar una tercera más épica"], 0),
        ("Incumplimiento reiterado de protocolo de cuidado:", "Reentrenamiento, límites y escalado si no corrige", ["Omitir por ser buena gente", "Solo humillación pública", "Quitar el rol en silencio"], 1),
        ("Coordinación con Dir. Médica:", "Flujos claros de órdenes y feedback de escena", ["Competencia tóxica", "Silencio total para no molestar", "Ignorar órdenes médicas por costumbre"], 2),
        ("Cierre de turno con incidente abierto:", "Dueño del seguimiento y estado del incidente", ["Para mañana sin dueño", "Oculto al siguiente equipo", "Chisme sin datos"], 1),
        ("Meta de control de Enfermería:", "Cuidado ordenado, seguro para la escena y enseñable al equipo", ["Solo tu protagonismo", "Sin registros porque es rol", "Improvisado sin estándares"], 0),
    ]),
    "DIR_RRHH": _p([
        ("Selección justa. Control mínimo:", "Perfil, evaluación, decisión motivada y registro", ["Solo amigos", "Secreto sin registro", "Sorteo público"], 1),
        ("Queja formal contra un jefe:", "Recepción, imparcialidad, investigación y resolución documentada", ["Borrar para proteger al jefe", "Publicar en anuncios", "Que investigue solo el acusado"], 2),
        ("Onboarding de nuevo personal:", "Normativa, organigrama, canales y expectativas del cargo", ["Ya se aprende", "Admin inmediato", "Solo color del rol"], 0),
        ("Inactividad injustificada reiterada:", "Aviso, plazos y medida según reglamento", ["Premio de rol", "Ban sorpresa", "Aviso eterno sin medida"], 1),
        ("Expedientes laborales. Acceso:", "Solo roles autorizados y necesidad de conocer", ["Todo el staff", "Publicar en general", "MD masivo a amigos"], 3),
        ("Despido de un miembro:", "Causa, proceso y comunicación formal", ["Inventar causa por rabia", "Solo un emoji", "Voto de visitantes"], 1),
        ("Postulado falsea experiencia:", "Rechazo, registro y norma antisuplantación", ["Aprobar igual", "Humillación pública innecesaria", "Promover a Director General"], 2),
        ("Conflicto de interés en contratación:", "Declararlo y abstenerse de decidir", ["Decidir igual porque conoces mejor", "Ocultarlo para agilizar", "Forzar a tu círculo"], 0),
        ("Caso grave con Cancillería:", "Informar con hechos y proponer medidas proporcionales", ["Rumores para forzar acción", "Ocultar datos críticos", "Difamar en público"], 1),
        ("¿Qué NO es control de RRHH?", "Imponer sanciones clínicas de tratamiento médico en escena", ["Altas, bajas y procesos formales", "Mediar conflictos laborales", "Custodiar expedientes y plazos"], 2),
        ("Favoritismo detectado:", "Reabrir criterio, corregir y documentar la corrección", ["Solo si hay escándalo público", "Vengar al favorecido", "Borrar todo rastro"], 1),
        ("Métrica útil de RRHH:", "Tiempos de cobertura de vacantes y calidad del onboarding", ["Cantidad de roles dados", "Likes", "Ignorar si hay gente online"], 0),
        ("Cambio de área solicitado:", "Evaluar disponibilidad, impacto y norma del destino", ["Negar siempre sin oír", "Aceptar sin consultar el destino", "Banear por pedir el cambio"], 3),
        ("Doble expediente contradictorio:", "Conciliar hechos con evidencias y una versión oficial", ["Dejar ambas activas", "Borrar el expediente", "Versión del amigo"], 1),
        ("Director presiona para contratar:", "Mantener el proceso y registrar intervención indebida si existe", ["Saltarte el proceso por jerarquía", "Filtrar al candidato en público", "Renunciar a evaluar"], 2),
        ("Escalado disciplinario proporcional:", "Graduar según gravedad, reiteración y norma publicada", ["Según el ánimo del día", "Siempre al máximo", "Solo advertencias eternas"], 0),
        ("Cierre de un caso de personal:", "Decisión, motivo, fecha y notificación al interesado", ["Sin motivo porque ya se sabe", "Filtrar como chisme", "Sin notificar al interesado"], 1),
        ("Onboarding incompleto a los 7 días:", "Completar brechas y asignar responsable de cierre", ["Culpar solo al nuevo", "Ignorar porque ya está dentro", "Repetir todo desde cero sin necesidad"], 2),
        ("Solicitud de acceso a expediente:", "Verificar autorización y registrar el acceso", ["Copia a cualquiera del staff", "Negar a roles autorizados sin causa", "Publicar extractos en general"], 1),
        ("Meta de control de RRHH:", "Procesos justos, trazables y alineados al reglamento", ["Rápidos aunque opacos", "Basados en amistades", "Improvisados sin registro"], 0),
    ]),
    "DIR_DOCENCIA": _p([
        ("Certificación válida. Control mínimo:", "Material, evaluación y registro de resultado/firmas según protocolo", ["Aprobar por amistad", "Solo un minuto en voz", "Pago OOC"], 1),
        ("Copia en examen de capacitación:", "Anular o aplicar política académica y dejar constancia", ["Aprobar igual para no drama", "Subir nota por pena", "Dar rol de Director"], 2),
        ("Instructor sesga notas a su círculo:", "Auditar, corregir y limitar al instructor si procede", ["Premiar su lealtad de equipo", "Cerrar Docencia completa por un caso", "Ignorar quejas sin evidencias"], 0),
        ("Temario desactualizado:", "Revisar con el área técnica y publicar versión vigente", ["Dejar versiones contradictorias", "Ocultar para que sea difícil", "Copiar de otro server sin adaptar"], 1),
        ("Coordinación con Dir. Médica:", "Validar que lo enseñado sea usable y coherente en escena", ["Bloquear a Médica por ego", "Que Médica ignore la formación", "Que Docencia ordene cada tratamiento"], 3),
        ("Registro de capacitaciones:", "Fecha, instructor, alumno y resultado verificable", ["Porque se recuerda", "Solo oral en voz", "Borrar al día siguiente"], 1),
        ("Aprobar por pena:", "Mantener el criterio del examen y ofrecer reintento según norma", ["Bajar nota de corte en secreto", "Burla pública", "Regalar el certificado"], 2),
        ("¿Qué NO es control de Docencia?", "Despedir personal de otras áreas sin proceso de RRHH", ["Diseñar evaluaciones", "Supervisar instructores y material", "Registrar certificaciones"], 0),
        ("Doble certificado contradictorio:", "Verificar evidencias y una emisión oficial corregida", ["Ambos válidos", "Borrar historial del alumno", "El más favorable al amigo"], 1),
        ("Carga excesiva de formadores:", "Planificar turnos de formación y evitar sobrecarga", ["Obligar 24/7 por vocación", "Prohibir formar", "Improvisar el mismo día"], 2),
        ("Alumno no entiende el material:", "Aclarar, ajustar explicación y mantener el estándar de evaluación", ["Insultar por no leer", "Bajar el estándar solo para ese caso", "Negar apoyo legítimo"], 1),
        ("Certificado sin evaluación:", "Rechazar si el protocolo exige examen o práctica", ["Rechazar solo si es nuevo", "Aceptar si lo pide un Director amigo", "Aceptar si ya tiene el color"], 0),
        ("Indicador útil docente:", "Tasa de aprobación coherente y quejas de sesgo revisadas", ["Certificados regalados", "Embeds bonitos", "Ignorar si hay muchos alumnos"], 3),
        ("Feedback al evaluado:", "Puntos concretos a mejorar sin humillación", ["Burla pública", "Omitir siempre", "Solo emojis de risa"], 1),
        ("Instructor improvisa reglas distintas:", "Unificar rúbrica y exigir adherencia", ["Libertad creativa total", "Sancionar alumnos por la inconsistencia", "Ocultar la rúbrica oficial"], 2),
        ("Revalidación de competencias:", "Mantener estándar mínimo actualizado del RP del área", ["Castigo arbitrario", "Quitar roles al azar", "No hacerla porque molesta"], 0),
        ("Publicación de resultados:", "Informar al alumno y al log del área según protocolo", ["Doxxeo innecesario", "Ocultar al interesado", "Insultos en el log"], 1),
        ("Director presiona para aprobar a alguien:", "Conservar independencia evaluadora y registrar presión indebida", ["Ceder por jerarquía", "Filtrar al alumno en público", "Cancelar el examen de todos"], 2),
        ("Cierre de convocatoria:", "Lista de resultados, pendientes de firma y archivo del acta", ["Lista mental", "Datos sensibles de más", "Borrar sin trazabilidad"], 1),
        ("Meta de control de Docencia:", "Formación justa, trazable y útil para el RP del hospital", ["Ornamental sin evaluación", "Favoritismos", "Sin material"], 0),
    ]),
    "DIR_LOGISTICA": _p([
        ("Emergencia con stock limitado:", "Priorizar criticidad clínica/operativa y registrar salidas", ["Al que más insiste", "Lo decorativo", "Negar todo para números bonitos"], 1),
        ("Inventario descuadrado:", "Auditoría, ajuste documentado y control preventivo", ["Inventar cifras", "No pasa nada", "Culpar al bot sin revisar"], 2),
        ("Pedido urgente fuera de protocolo:", "Evaluar, entregar si procede y regularizar con registro", ["Negar siempre", "Entregar a cualquiera sin control", "Borrar el pedido"], 0),
        ("Almacén restringido. Control de acceso:", "Quién entra, por qué y qué se mueve", ["Libre si es staff", "Sin registro de movimiento", "Prohibido aunque haya necesidad"], 1),
        ("Pérdida de material:", "Investigar causa, responsabilidad y prevención", ["Ocultar el faltante", "Culpar al azar", "Cerrar el hospital por faltante menor"], 3),
        ("Coordinación con Médica:", "Previsión, canal de solicitud y confirmación de entrega", ["No hablar nunca", "Negar críticos sin alternativa", "Entregar sin anotar"], 1),
        ("Reporte a Dir. General:", "Niveles de stock, riesgos y acciones con dueño", ["Solo memes", "Solo quejas", "Falsos para no preocupar"], 2),
        ("Turnos logísticos. Objetivo:", "Cobertura estable sin quemar al equipo", ["Una persona 24/7 forzada", "Cobertura cero", "Improvisar cada día"], 0),
        ("Área pide de más sin justificación:", "Cuestionar necesidad, ajustar cantidad y registrar", ["Entregar todo sin control", "Insultar al solicitante", "Ignorar el pedido para siempre"], 1),
        ("¿Qué NO es control de Logística?", "Sancionar clínicamente a un médico por un tratamiento de escena", ["Inventario y accesos", "Priorizar insumos críticos", "Reportar desabastecimiento"], 2),
        ("Doble salida del mismo ítem:", "Conciliar movimientos y corregir el registro oficial", ["Dejar ambas sin revisión", "Borrar el inventario", "Culpar sin timestamps"], 1),
        ("Proveedor interno incumple plazos:", "Aviso, alternativa temporal y escalado si reitera", ["Premiar al proveedor", "Improvisación eterna", "Cerrar el área usuaria"], 0),
        ("Indicador útil logístico:", "Quiebres de stock crítico y tiempo de reposición", ["Mensajes en el canal", "Ignorar si el Director está online", "Caos divertido"], 3),
        ("Demora de entrega:", "Avisar impacto y nueva ETA al responsable del área", ["Nada esperando que no se noten", "Mentir una hora imposible", "Humillar al solicitante en público"], 1),
        ("Plan de stock mínimo:", "Evitar cero en insumos esenciales de operación/RP", ["Que nadie pida nunca", "Evitar inventario porque aburre", "Evitar transparencia"], 2),
        ("Disputa entre áreas por el mismo lote:", "Prioridad institucional documentada y comunicar", ["Al amigo del Dir. Logística", "Al que grita más", "Tirar el lote para que no peleen"], 0),
        ("Acceso indebido al almacén:", "Cortar acceso, reportar e investigar movimiento", ["Cortar sin investigar qué salió", "Doxxing del implicado", "Ignorar porque no faltó mucho"], 1),
        ("Cierre diario de inventario:", "Entradas, salidas, faltantes y responsable del conteo", ["Ya está en la cabeza", "Inventar para cuadrar bonito", "Borrar al cerrar el PC"], 2),
        ("Presión para saltarse registro solo esta vez:", "Mantener registro o excepción documentada con límite", ["Ceder siempre por prisa", "Humillar al solicitante", "Eliminar el historial anterior"], 1),
        ("Meta de control de Logística:", "Disponibilidad trazable de recursos críticos con cuentas claras", ["Caos sin números", "Solo el círculo del Director", "Reportes falsos"], 0),
    ]),
    "JEFE_SEGURIDAD": _p([
        ("Intruso en área restringida:", "Identificar, contener según protocolo y reportar", ["Ignorar si no toca nada", "Ban sin evidencia de escena", "Huir de la zona"], 1),
        ("Uso de fuerza en RP:", "Proporcional, escalonado y justificado en la escena", ["Máximo desde el primer segundo", "Al azar para que sea épico", "Prohibido ante riesgo claro"], 2),
        ("Incidente violento cerca de atención clínica:", "Asegurar la escena y permitir asistencia segura", ["Bloquear a todo el personal médico", "Evacuar sin informar", "Cerrar el RP clínico"], 0),
        ("Informe de incidente:", "Hechos, horarios, involucrados y acciones tomadas", ["Opiniones sin marcar", "Omitir porque ya se sabe", "Insultos a involucrados"], 1),
        ("Guardia abusa de autoridad:", "Investigar, sancionar o reentrenar según norma", ["Cubrir por lealtad", "Ascender para motivar", "Ignorar quejas reiteradas"], 3),
        ("Acceso a quirófano:", "Verificar rol y necesidad de la escena", ["Pasar si parece staff", "Prohibir a todo personal clínico", "Sin criterio estable"], 1),
        ("Amenaza OOC en canal del hospital:", "Separar IC/OOC, documentar y escalar a staff admin", ["Tratar solo como RP", "Responder con más amenazas", "Borrar sin registro interno"], 2),
        ("Entrenamiento del equipo:", "Protocolos, comunicación y proporcionalidad", ["Caos improvisado", "Solo chat sin criterios", "Enseñar a ignorar el reglamento"], 0),
        ("Rondas y puestos:", "Disuasión, detección temprana y cobertura de puntos clave", ["Solo decoración", "Puestos vacíos crónicos", "Solo RP de café"], 1),
        ("¿Qué NO es control de Seguridad?", "Diagnosticar y tratar clínicamente al paciente en lugar del médico", ["Controlar accesos sensibles", "Contener incidentes de RP", "Reportar riesgos a dirección"], 2),
        ("Doble versión de un incidente:", "Contrastar evidencias y fijar relato oficial interno", ["Publicar ambas para drama", "Elegir la del amigo", "Borrar evidencias incómodas"], 1),
        ("Civil altera recepción:", "Contención proporcional y reporte si escala", ["Fuerza máxima sin escalón", "Ignorar peligro claro", "Ban al primer grito"], 0),
        ("Indicador útil de seguridad:", "Incidentes con informe completo y puestos críticos cubiertos", ["Cantidad de PK", "Ignorar si no hubo ban", "Celebrar sin aprendizaje"], 3),
        ("Crisis con Cancillería:", "Hechos, plan de contención y estado de canales/accesos", ["Ocultar para no preocupar", "Exagerar sin plan", "Culpar a Cancillería"], 1),
        ("Presión para inventar delito y PK:", "Exigir justificación de RP seria y proporcional", ["Permitir PK por aburrimiento", "PK obligatorio en anuncios", "Ocultar el motivo al staff"], 2),
        ("Fallo de cobertura en puesto clave:", "Reasignar, registrar el hueco y corregir el plan de turnos", ["Culpar en público sin plan", "Ignorar el hueco", "Cerrar el hospital siempre"], 0),
        ("Evidencias de un incidente:", "Conservar ordenado para staff autorizado", ["Publicar todo en general", "Borrar al terminar la escena", "Falsificar para que cierre mejor"], 1),
        ("Admin pide saltarse identificación rápido:", "Mantener protocolo o excepción documentada por riesgo real", ["Ceder por rango Discord", "Humillar al Admin en general", "Eliminar identificación para todos"], 2),
        ("Cierre de incidente:", "Informe breve, estado de la zona y retorno a cobertura normal", ["Abandonar el puesto", "Doxxing de involucrados", "Premiar abuso de fuerza"], 1),
        ("Meta de control de Seguridad:", "Escenas seguras, accesos controlados y autoridad proporcional", ["Caos para contenido", "Abuso de poder", "Sin reportes ni aprendizaje"], 0),
    ]),
}
