# -*- coding: utf-8 -*-
"""Banco de 20 preguntas RP (nivel accesible) por dirección."""
from __future__ import annotations

from typing import Dict, List, Tuple

# (pregunta, [A,B,C,D], índice correcta 0-3)
Q = List[Tuple[str, List[str], int]]


def _q(texto: str, buena: str, malas: List[str]) -> Tuple[str, List[str], int]:
    ops = [buena] + malas[:3]
    # barajar fijo por texto para no dejar siempre A correcta en UI…
    # En el examen el índice se guarda; mantenemos buena en posición 1 (B) por claridad RP
    orden = [malas[0], buena, malas[1], malas[2]] if len(malas) >= 3 else [buena, *malas, "Ninguna de las anteriores"]
    while len(orden) < 4:
        orden.append("Ninguna de las anteriores")
    correcta = orden.index(buena)
    return (texto, orden[:4], correcta)


def _pack(items: List[Tuple[str, str, List[str]]]) -> Q:
    return [_q(t, b, m) for t, b, m in items]


BANCO: Dict[str, Q] = {
    "CANCILLER": _pack([
        ("¿Qué representa el Canciller en el hospital de RP?", "La autoridad que coordina y representa al hospital", ["Solo un médico de planta", "Un visitante con rol de color", "Solo el bot del servidor"]),
        ("Si dos direcciones discuten en OOC, lo correcto es:", "Hablar con respeto y usar canales de staff", ["Insultarse en general", "Cerrar el servidor", "Ignorar las normas"]),
        ("Una decisión importante del Canciller debería:", "Quedar clara y, si hace falta, documentada", ["Solo un MD sin rastro", "Solo memes", "No comunicarse nunca"]),
        ("¿Quién está por encima del Canciller en el organigrama?", "Fundador / Owner y autoridades del servidor", ["Un residente", "Cualquier visitante", "El bot de tickets"]),
        ("En una crisis grande de rol, el Canciller debería:", "Ayudar a ordenar y apoyar a las direcciones", ["Desaparecer", "Banear a todos sin mirar", "Solo mirar memes"]),
        ("El Vice Canciller sirve para:", "Apoyar al Canciller y cubrir cuando haga falta", ["Reemplazar al Owner para siempre", "Solo poner embeds", "Solo la economía"]),
        ("Si alguien filtra info privada de staff:", "Se trata como falta seria según el reglamento", ["Se premia", "No pasa nada", "Se publica otra vez en general"]),
        ("Representar al hospital ante otros implica:", "Cuidar la imagen y seguir lo acordado", ["Decir cualquier cosa", "Pelear con otros servers", "No responder nunca"]),
        ("¿El Canciller debe conocer el organigrama?", "Sí, para dirigir con orden", ["No hace falta", "Solo los roles de color", "Solo tickets"]),
        ("Si un director no cumple sus funciones:", "Se habla el tema y se sigue el reglamento", ["Se ignora siempre", "Se premia", "Se le da más poder"]),
        ("Los anuncios oficiales del hospital deberían ser:", "Claros y en el canal correcto", ["Solo en DMs random", "Insultos", "Secretos para siempre"]),
        ("¿Se puede saltar el organigrama por comodidad?", "No, se respeta la cadena de mando", ["Sí siempre", "Solo los viernes", "Solo en memes"]),
        ("En una reunión de direcciones, el Canciller:", "Modera y busca acuerdos", ["Ignora a todos", "Solo pone música", "Banear a los que hablan"]),
        ("La confidencialidad en Cancillería significa:", "No compartir info sensible sin necesidad", ["Publicar todo en general", "Vender datos", "Borrar el server"]),
        ("Si el Owner da una orden institucional:", "Se acata y se coordina su aplicación", ["Se ignora", "Se pelea en público", "Se borra el mensaje"]),
        ("Un buen Canciller en RP:", "Comunica, organiza y da ejemplo", ["Solo tiene el rol y no hace nada", "Toxiquea al staff", "Cierra canales por aburrimiento"]),
        ("¿Qué hacer si hay drama OOC grave?", "Contener, documentar y escalar a quienes corresponde", ["Echar más leña", "Banear sin mirar a todos", "Ignorar por completo"]),
        ("Las sanciones a un director deben ser:", "Con proceso y proporcionalidad", ["Públicas y humillantes sin causa", "Aleatorias", "Solo un emoji"]),
        ("¿El Canciller sustituye al médico en cada paciente?", "No, no es su función clínica diaria", ["Sí siempre", "Solo los lunes", "Sí si tiene aburrimiento"]),
        ("Al terminar un conflicto entre áreas:", "Dejar claro el acuerdo y seguir el rol", ["Dejar todo a medias", "Borrar evidencias útiles", "Premiar al que gritó más"]),
    ]),
    "VICE_CANCILLER": _pack([
        ("El Vice Canciller actúa sobre todo cuando:", "El Canciller no está o pide apoyo", ["Quiere mandar sobre el Canciller", "Un visitante lo ordena", "Nunca puede hacer nada"]),
        ("Si el Canciller corrige tu decisión:", "La respetas y sigues el organigrama", ["La ignoras", "Sancionas al Canciller", "Cierras su ticket"]),
        ("En un conflicto entre dos áreas:", "Medias con calma y buscas solución justa", ["Te pones de un lado sin escuchar", "Borras canales", "Baneas a ambos"]),
        ("La info sensible de Cancillería:", "Se cuida y solo se comparte con quien debe", ["Se publica en general", "Se vende", "Se borra siempre al instante"]),
        ("Trabajar con Dirección General es:", "Coordinarse para que el hospital funcione", ["Competir y no hablarse", "Solo pelear en staff", "Ignorar la operación"]),
        ("Si un director cuestiona tu cargo:", "Explicas el organigrama con respeto", ["Respondes con insultos", "Renuncias en silencio", "Baneas sin proceso"]),
        ("Un buen Vice Canciller:", "Está disponible, comunica y apoya al equipo", ["Solo aparece por el rol", "Nunca entra a canales de dirección", "Ignora las normas"]),
        ("En una emergencia de rol priorizas:", "Orden, seguridad de canales y ayudar al staff", ["Tu escena personal", "Cerrar todos los tickets sin mirar", "Salirte del server"]),
        ("¿Puedes inventar reglas que contradigan al Canciller?", "No, se sigue la línea institucional", ["Sí siempre", "Solo en voz", "Solo con memes"]),
        ("Documentar una decisión interina sirve para:", "Que quede claro qué se hizo y por qué", ["Nada", "Trollear", "Borrar pruebas"]),
        ("Si no sabes cómo actuar:", "Consultas al Canciller o a autoridades", ["Improvisas daño al server", "Ignoras el problema", "Baneas al azar"]),
        ("El tono en canales de staff debe ser:", "Profesional y respetuoso", ["Tóxico", "Solo mayúsculas", "Insultos"]),
        ("Apoyar al Canciller implica:", "Cumplir encargos y mantener el orden", ["Hacer lo contrario", "Ocultarle información importante", "Burlarse en público"]),
        ("¿El Vice es lo mismo que Admin en jefe?", "No: uno es autoridad institucional y otro staff de server", ["Sí, es igual", "Admin manda sobre Canciller", "Vice solo hace tickets"]),
        ("Si hay queja contra ti:", "La atiendes con seriedad según el proceso", ["La borras", "Insultas al quejoso", "La ignoras siempre"]),
        ("Comunicar ausencias sirve para:", "Que el equipo sepa quién cubre", ["Nada", "Generar caos", "Ocultar inactividad siempre"]),
        ("En reuniones, el Vice debería:", "Aportar y tomar nota de acuerdos", ["Dormir el rol", "Interrumpir para troll", "Banear asistentes"]),
        ("¿Se puede filtrar actas de Cancillería?", "No, es información restringida", ["Sí al general", "Sí a otros servers", "Sí por puntos"]),
        ("Relación con RRHH en un caso serio:", "Coordinar con hechos y respeto", ["Ocultar todo", "Difamar", "Ignorar RRHH"]),
        ("Al cubrir al Canciller tu meta es:", "Mantener estabilidad hasta que regrese", ["Cambiar todo el organigrama", "Cerrar direcciones", "Promoverte a Owner"]),
    ]),
    "DIR_GENERAL": _pack([
        ("Dirección General se enfoca en:", "Coordinar que las direcciones trabajen juntas", ["Solo quirófano", "Solo roles de color", "Solo fiestas"]),
        ("Si Médica y Logística no se entienden:", "Hablas con ambas y buscas acuerdo", ["Dejas que peleen en público", "Cierras un área", "Ignoras"]),
        ("Director inactivo sin avisar:", "Se contacta y se sigue el reglamento", ["No pasa nada", "Se promociona", "Ban sin hablar"]),
        ("Un cambio de reglas amplio debería:", "Comunicarse bien a áreas y staff", ["Publicarse sin avisar", "Quedar solo en un MD", "Ocultarse"]),
        ("En un incidente grande, Dir. General:", "Ayuda a organizar y mantener la operación", ["Se desconecta", "Solo memes", "Banea pacientes"]),
        ("Reportar a Cancillería sirve para:", "Informar lo importante con claridad", ["Quejarse sin datos", "Difamar", "Nunca informar"]),
        ("Delegar a un jefe de servicio es:", "Confiar tareas y seguir pendiente del resultado", ["Abandonar el área", "Prohibir trabajar", "Ceder el cargo para siempre"]),
        ("Lo que NO es función típica de Dir. General:", "Ser el médico tratante de cada paciente", ["Coordinar áreas", "Ayudar en crisis", "Cuidar políticas del hospital"]),
        ("Prioridades de la semana deberían:", "Estar claras para el equipo", ["Ser secretas siempre", "Cambiar cada hora sin aviso", "No existir"]),
        ("Si un área pide ayuda:", "Escuchas y coordinas apoyo razonable", ["Ignoras", "Te burlas", "Cierras el canal"]),
        ("La comunicación entre direcciones debe ser:", "Respetuosa y por canales adecuados", ["Solo insultos", "Solo rumores", "Inexistente"]),
        ("¿Dir. General reemplaza a Cancillería?", "No, son roles distintos que se complementan", ["Sí siempre", "Sí los fines de semana", "Sí si hay aburrimiento"]),
        ("Un protocolo nuevo se difunde:", "Con aviso claro a quien lo debe aplicar", ["En secreto", "Solo a amigos", "Nunca"]),
        ("Si hay falta de personal en varias áreas:", "Se reorganiza y se informa", ["Se cierra el hospital en silencio", "Se culpa a un visitante", "Se ignora"]),
        ("Las metas de operación se revisan:", "De forma periódica y realista", ["Nunca", "Solo con memes", "Cada minuto"]),
        ("Conflicto OOC entre directores:", "Se media fuera de escena y con respeto", ["Se pelea en rol médico", "Se banea a ambos sin hablar", "Se publica para drama"]),
        ("¿Se debe mentir en reportes a Cancillería?", "No, se informan hechos", ["Sí para quedar bien", "Solo a veces", "Sí siempre"]),
        ("Apoyar a Seguridad en un incidente es:", "Coordinar para proteger la operación y el rol", ["Ignorar Seguridad", "Bloquear a todos los médicos", "Cerrar sin avisar"]),
        ("Un buen Director General:", "Organiza, comunica y da seguimiento", ["Solo tiene el título", "Toxiquea", "Desaparece en crisis"]),
        ("Al terminar el día de operación conviene:", "Dejar pendientes claros al siguiente equipo", ["No decir nada", "Borrar logs útiles", "Culpar al azar"]),
    ]),
    "DIR_MEDICO": _pack([
        ("En una emergencia de rol lo importante es:", "Organizar quién hace qué y cuidar la escena", ["Improvisar sin hablar", "Cerrar el voice", "Salirse del rol"]),
        ("Un residente se equivoca. ¿Qué haces?", "Lo corriges con respeto y le enseñas", ["Lo humillas en público", "Lo ignoras", "Lo expulsas sin hablar"]),
        ("Trabajar con enfermería en escena es:", "Coordinar órdenes y cuidar al paciente de rol", ["Ignorar a enfermería", "Prohibirles entrar", "Solo pelear en OOC"]),
        ("Pelea OOC entre médicos en medio del rol:", "Separar IC/OOC y resolver fuera de escena", ["Seguir discutiendo en escena", "Banear sin más", "Borrar el canal"]),
        ("Un buen Director Médico:", "Apoya al equipo y mantiene orden en el rol clínico", ["Solo tiene el rol y no organiza", "No responde nunca", "Ignora a residentes"]),
        ("La historia clínica en rol debería tener:", "Qué le pasa, qué se hizo y quién atendió", ["Solo un emoji", "Nada nunca", "Solo el color del rol"]),
        ("Respecto a Docencia:", "Apoyar que la gente se forme bien para el rol", ["Bloquear todo", "Ignorar capacitaciones", "Dar certificados sin criterio"]),
        ("Un médico no quiere atender sin motivo de rol:", "Se habla y se asegura cobertura según normas", ["Dejar urgencias vacía siempre", "Cerrar el hospital", "Sancionar al paciente"]),
        ("¿Se inventan diagnósticos imposibles solo por troll?", "No, se mantiene coherencia de RP", ["Sí siempre", "Sí si aburre", "Sí en anuncios"]),
        ("En quirófano de rol conviene:", "Roles claros y comunicación", ["Caos total", "Silencio absoluto obligatorio sin plan", "Echar a enfermería por defecto"]),
        ("Un interno pregunta algo básico:", "Se responde y se enseña", ["Se ridiculiza", "Se ignora", "Se le quita el rol al instante"]),
        ("Priorizar pacientes en urgencias:", "Por gravedad de la escena", ["Por rol de Discord más alto", "Por quien escribe más rápido", "Al azar siempre"]),
        ("Si no sabes un protocolo clínico de RP:", "Consultas material/normas del área", ["Inventas daño al paciente de rol", "Abandonas", "Insultas al equipo"]),
        ("Transferir un paciente a otra área:", "Se informa qué tiene y qué se hizo", ["Se manda sin info", "Se oculta todo", "Se borra el caso"]),
        ("¿El Director Médico está solo en el hospital?", "No, coordina con otras direcciones", ["Sí, manda en todo el server", "Sí, incluso sobre el Owner", "Solo hace tickets"]),
        ("Errores graves repetidos de un médico:", "Se documentan y se escalan según reglamento", ["Se premian", "Se ignoran siempre", "Se publican para humillar"]),
        ("Consentimiento en RP (cuando aplica):", "Se respeta salvo emergencia justificada en rol", ["Nunca importa", "Solo para staff", "Se ignora siempre"]),
        ("Turnos médicos sirven para:", "Haber cobertura y orden", ["Nada", "Castigar gente", "Cerrar urgencias por gusto"]),
        ("Hablar mal de pacientes en general:", "No; se cuida el respeto y la confidencialidad de RP", ["Está bien siempre", "Es obligatorio", "Da puntos"]),
        ("Al cerrar una escena médica:", "Se deja claro el estado del paciente y el plan", ["Se desaparece sin decir nada", "Se trolla al paciente", "Se borra el chat útil siempre"]),
    ]),
    "DIR_ENFERMERIA": _pack([
        ("¿A quién atiendes primero con varios pacientes?", "Al más grave o que más cuidado necesita", ["Al primero en llegar siempre", "Al de mayor rol Discord", "Al que más pide en chat"]),
        ("Antes de dar un medicamento en rol:", "Confirmas qué se pidió, a quién y lo registras", ["Inventas la dosis", "No preguntas", "Se lo das a otro"]),
        ("Un auxiliar se equivoca:", "Corriges, explicas y avisas si es grave", ["Te ríes y no dices nada", "Baneas al momento", "Ignoras siempre"]),
        ("Coordinar con el médico es:", "Seguir el plan, avisar cambios y preguntar dudas", ["Cambiar órdenes sin avisar", "Nunca hablarle", "Solo pelear OOC"]),
        ("Falta personal en el turno:", "Reorganizas tareas y pides apoyo si hace falta", ["Abandonas pacientes", "Cierras en silencio", "Das rol de enfermero a cualquiera sin proceso"]),
        ("Datos del paciente en RP:", "Se cuidan; solo con quien atiende", ["Se publican en general", "Se usan para troll", "No importan"]),
        ("Liderar en una crisis de rol:", "Repartes tareas claras al equipo", ["Gritas sin organizar", "Te sales de la escena", "Dejas libre al caos"]),
        ("Formar auxiliares:", "Lo impulsa Enfermería (con Docencia si aplica)", ["No le importa a nadie", "Solo Seguridad", "Solo el Owner"]),
        ("Higiene/aislamiento en RP sirve para:", "Dar coherencia y calidad a la escena", ["Nada", "Solo decorar", "Molestar sin sentido"]),
        ("Si el médico da una orden confusa:", "Pides aclaración antes de actuar mal", ["Haces lo contrario a propósito", "Ignoras al paciente", "Insultas al médico"]),
        ("Registro de enfermería debería ser:", "Claro y útil para el equipo", ["Opcional siempre", "Solo mental", "Copia de memes"]),
        ("Conflictos entre enfermeros en turno:", "Separan, escuchan y median", ["Pelea en el pasillo de rol", "Banean al más nuevo", "Cierran el turno"]),
        ("Prioridad de cuidados se basa en:", "Gravedad y necesidad", ["Simpatía personal", "Rango Discord", "Orden alfabético del nick"]),
        ("¿Enfermería reemplaza al Director Médico?", "No, se complementan en la atención", ["Sí en todo", "Sí para sancionar", "Sí para el organigrama entero"]),
        ("Un paciente de rol está inquieto:", "Se aborda con calma y protocolo del área", ["Se insulta", "Se ignora por completo", "Se banea del server al instante"]),
        ("Entregar turno a otro equipo:", "Informas pendientes y pacientes críticos", ["Te vas sin decir nada", "Borras notas útiles", "Mientes el estado"]),
        ("Material faltante se reporta a:", "Logística / canales del área según norma", ["Nadie", "Solo memes", "Visitantes al azar"]),
        ("Un buen Director de Enfermería:", "Organiza turnos, enseña y cuida el estándar de RP", ["Solo el título", "Toxiquea al equipo", "Desaparece en códigos"]),
        ("¿Se puede inventar una vía o dosis absurda por troll?", "No, se mantiene coherencia de RP", ["Sí", "Sí si hay aburrimiento", "Sí en anuncios"]),
        ("Trabajo en equipo con médicos implica:", "Comunicación clara y respeto mutuo", ["Competencia tóxica", "Silencio total obligatorio", "Ignorar órdenes siempre"]),
    ]),
    "DIR_RRHH": _pack([
        ("Al aceptar a alguien lo justo es:", "Revisar perfil, normas y dejar registro", ["Solo amigos sin criterios", "Vender el puesto", "Aceptar sin leer"]),
        ("Queja formal contra un jefe:", "Se recibe, investiga con imparcialidad y se resuelve", ["Se borra", "Se publica para drama", "Se ignora si es popular"]),
        ("Un nuevo miembro debería recibir:", "Normas básicas, canales y expectativas del cargo", ["Nada", "Admin al instante", "Solo un color sin explicación"]),
        ("Inactividad larga sin avisar:", "Se aplica el reglamento (avisos/medidas)", ["Se premia", "Se ignora siempre", "Se promociona"]),
        ("Expedientes de personal:", "Solo quien tiene permiso los ve", ["Públicos para todo el server", "MD a todos", "En general"]),
        ("Un despido debería:", "Tener causa clara y aviso formal", ["Ser un insulto sin motivo", "Solo un emoji", "Voto de visitantes"]),
        ("Postulado que miente experiencia:", "Se rechaza y se deja constancia", ["Se aprueba igual", "Se le da Director General", "Se ignora"]),
        ("RRHH y Cancillería en caso grave:", "Se comunican con hechos y soluciones", ["Se ocultan info", "Pelean en público", "No hablan nunca"]),
        ("El onboarding sirve para:", "Integrar bien al nuevo al hospital", ["Confundirlo", "Darle ban de bienvenida", "Nada"]),
        ("¿RRHH pone sanciones médicas clínicas?", "No; se coordina con el área que corresponde", ["Sí siempre", "Sí por aburrimiento", "Sí en voz"]),
        ("Favoritismo en contrataciones:", "Se evita; se usan criterios claros", ["Es obligatorio", "Es lo normal", "Se premia"]),
        ("Documentar procesos de selección:", "Ayuda a la transparencia del área", ["No sirve", "Solo para troll", "Es ilegal en Discord siempre"]),
        ("Si hay demasiadas quejas de un área:", "Se revisa el patrón y se actúa con datos", ["Se ignora", "Se borra el canal de quejas", "Se culpa a un visitante al azar"]),
        ("Roles de personal se otorgan:", "Según proceso y cargo real de RP", ["Al azar", "Por pagar OOC", "Por gritar en general"]),
        ("Un miembro pide cambio de área:", "Se evalúa disponibilidad y normas", ["Se niega siempre sin oír", "Se acepta sin hablar con nadie", "Se le banea"]),
        ("Confidencialidad de casos RRHH:", "No se comenta en público sin necesidad", ["Se cuenta en general", "Se usa para drama", "Se vende"]),
        ("Buen Director de RRHH:", "Es justo, ordenado y claro con la gente", ["Solo el título", "Toxiquea postulantes", "Desaparece en procesos"]),
        ("¿Se puede contratar sin leer el reglamento?", "No, el postulante debe conocer lo básico", ["Sí", "Sí si es amigo", "Sí los domingos"]),
        ("Escalas de sanción laboral de RP:", "Siguen el reglamento del hospital", ["Son inventadas en el momento por rabia", "No existen nunca", "Las pone un visitante"]),
        ("Al cerrar un expediente:", "Queda registro de la decisión y el motivo", ["Se borra todo siempre", "Solo un emoji", "Se publica el doxxing"]),
    ]),
    "DIR_DOCENCIA": _pack([
        ("Una certificación debería basarse en:", "Estudiar, evaluar y cumplir el proceso", ["Solo amistad", "Pago OOC", "Un minuto en voz"]),
        ("Si alguien copia en el examen:", "Se aplica la norma de Docencia (anular/sancionar según regla)", ["Se aprueba igual", "Se sube la nota", "Se le da Director"]),
        ("El material de estudio debería ser:", "Claro y acorde a las normas de RP", ["Imposible a propósito", "Solo memes", "Secreto eterno"]),
        ("Docencia y Dirección Médica:", "Se coordinan para que lo enseñado sirva en el rol", ["Se evitan", "Solo pelean", "Ignoran certificaciones"]),
        ("Guardar quién aprobó un curso sirve para:", "Orden: fecha, resultado y formador", ["Nada", "Borrar evidencias", "Trollear"]),
        ("Instructor que favorece a su círculo:", "Revisas el caso y corriges si hubo injusticia", ["Lo premias", "Cierras Docencia para siempre", "Ignoras quejas"]),
        ("Objetivo de capacitar:", "Que la gente rolee mejor y con más calidad", ["Solo llenar de roles", "Sancionar por diversión", "Evitar que entren"]),
        ("Emitir certificado sin evaluación:", "No es correcto si el protocolo pide examen/práctica", ["Está bien siempre", "Es obligatorio cada día", "Solo Seguridad lo hace"]),
        ("Un alumno no entiende el temario:", "Se explica de nuevo con claridad", ["Se insulta", "Se le niega todo apoyo", "Se le banea"]),
        ("¿Docencia reemplaza a RRHH en despidos?", "No, cada área tiene su función", ["Sí siempre", "Sí los viernes", "Sí por aburrimiento"]),
        ("Clases o guías deberían:", "Ser útiles para el RP del hospital", ["Ser confusas a propósito", "Solo flexear", "Copiar sin revisar"]),
        ("Revalidar conocimientos sirve para:", "Mantener un nivel mínimo de calidad", ["Molestar sin sentido", "Quitar roles al azar", "Nada"]),
        ("Registrar capacitaciones:", "Permite trazabilidad y orden", ["Es inútil", "Solo oral para siempre", "Se borra al día siguiente siempre"]),
        ("Si Médica pide un curso nuevo:", "Se evalúa y se arma con criterio del área", ["Se niega siempre", "Se inventa basura", "Se ignora"]),
        ("Buen Director de Docencia:", "Organiza formación justa y clara", ["Solo el título", "Vende certificados", "Desaparece en evaluaciones"]),
        ("¿Se puede aprobar a alguien por pena?", "No; se mantiene el criterio del examen", ["Sí siempre", "Sí si es amigo", "Sí en voz"]),
        ("Material desactualizado:", "Se revisa y se actualiza", ["Se deja para siempre", "Se esconde", "Se culpa a un alumno"]),
        ("Feedback al alumno:", "Se da con respeto y puntos a mejorar", ["Solo humillación", "Nunca", "Solo emojis de risa"]),
        ("Coordinar instructores implica:", "Misma línea de evaluación y temas", ["Cada uno inventa reglas secretas", "Competir tóxicamente", "No hablarse"]),
        ("Al publicar resultados:", "Se informa al alumno y al log del área si aplica", ["Se doxea", "Se oculta siempre al interesado", "Se publica insultos"]),
    ]),
    "DIR_LOGISTICA": _pack([
        ("En emergencia, ¿qué va primero?", "Lo más importante para atender y mantener el hospital", ["Lo que pida el más ruidoso", "Nada de stock", "Solo decoración"]),
        ("Inventario que no cuadra:", "Se revisa, se corrige y se deja registro", ["Se inventan números", "Se ignora", "Se culpa al bot sin mirar"]),
        ("Con Dirección Médica, Logística debería:", "Anticipar pedidos y tener canales claros", ["No hablar nunca", "Negar todo", "Entregar sin anotar"]),
        ("Pedido urgente fuera de lo normal:", "Se evalúa, se entrega si procede y se regulariza", ["Siempre se niega", "Se da a cualquiera sin control", "Se borra el pedido"]),
        ("Almacén restringido:", "Control de quién entra y qué se mueve", ["Acceso libre", "Ningún control", "Solo un emoji sin reglas"]),
        ("Si se pierde material:", "Se investiga y se evita que se repita", ["Se oculta", "Se culpa al azar", "Se cierra el hospital"]),
        ("Reportar a Dir. General sirve para:", "Avisar stock y problemas reales", ["Solo memes", "Nunca informar", "Quejas sin datos"]),
        ("Organizar turnos busca:", "Cobertura sin quemar al equipo", ["Una persona 24/7", "Área vacía", "Prohibir el almacén"]),
        ("Un área pide de más sin justificación:", "Se pregunta y se ajusta a lo necesario", ["Se entrega todo sin control", "Se insulta", "Se ignora para siempre"]),
        ("Etiquetar / ordenar el inventario sirve para:", "Encontrar rápido lo que hace falta", ["Nada", "Confundir", "Decorar solo"]),
        ("¿Logística opera sola sin hablar con nadie?", "No, se coordina con las áreas que consumen", ["Sí siempre", "Sí los domingos", "Sí por aburrimiento"]),
        ("Falta un insumo crítico:", "Se avisa y se busca alternativa", ["Se calla", "Se culpa a Enfermería sin datos", "Se cierra voz"]),
        ("Buen Director de Logística:", "Orden, previsión y comunicación", ["Solo el título", "Pierde todo el stock a propósito", "Desaparece en emergencias"]),
        ("Entregas sin registro:", "Dificultan el control; mejor anotar", ["Son ideales siempre", "Obligatorias para troll", "Reemplazan el inventario"]),
        ("Prioridad de reposición:", "Lo que más impacta la atención del hospital", ["Lo más bonito", "Lo que pide un visitante", "Nada"]),
        ("Si hay disputa por material:", "Se media con reglas claras del área", ["Se pelea en general", "Se banea a ambos", "Se tira el stock"]),
        ("Plan mínimo de stock:", "Ayuda a no quedarse en cero en lo esencial", ["No sirve", "Es un mito", "Solo para memes"]),
        ("Comunicar demoras de entrega:", "Se avisa al área que espera", ["Se oculta siempre", "Se miente", "Se ignora el pedido"]),
        ("¿Logística sanciona médicos por clínica?", "No; no es su función", ["Sí siempre", "Sí por aburrimiento", "Sí en tickets de quejas médicas"]),
        ("Al cerrar inventario del día:", "Queda claro qué entró, qué salió y qué falta", ["Se borra todo", "Solo un emoji", "Se inventa al azar"]),
    ]),
    "JEFE_SEGURIDAD": _pack([
        ("Intruso en zona restringida:", "Se identifica, se sigue protocolo y se reporta", ["Se ignora", "Ban sin mirar el rol", "Se huye"]),
        ("Uso de fuerza en RP de seguridad:", "Proporcional y justificado en la escena", ["Máximo siempre", "Aleatorio por diversión", "Prohibido en todo caso"]),
        ("Incidente violento cerca de pacientes:", "Se asegura la zona y se deja atender con seguridad", ["Se bloquea a todos los médicos", "Se evacúa sin avisar", "Se cierra el rol médico"]),
        ("Un informe de seguridad incluye:", "Qué pasó, cuándo y qué se hizo", ["Solo opiniones", "Nada escrito", "Insultos"]),
        ("Guardia que abusa del rol:", "Se investiga y se corrige o sanciona según normas", ["Se le cubre", "Se le asciende", "Se ignoran quejas"]),
        ("Acceso a quirófano / áreas sensibles:", "Se verifica quién es y por qué entra", ["Libre para cualquiera", "Prohibido a todo staff médico", "Sin control nunca"]),
        ("Amenaza OOC en un canal:", "Se separa de IC, se documenta y se escala al staff", ["Se trata solo como RP", "Se responde con más amenazas", "Se borra sin rastro y ya"]),
        ("Entrenar al equipo sirve para:", "Protocolos y criterio en el rol", ["Solo rellenar tiempo", "Caos a propósito", "Ignorar el reglamento"]),
        ("Rondas / puestos fijos sirven para:", "Disuasión y detección temprana", ["Solo decoración", "Nada", "Solo RP de café"]),
        ("Relación con Cancillería en crisis:", "Informar con hechos y plan de contención", ["Ocultar el incidente", "Culpar a Cancillería", "Cerrar sin avisar"]),
        ("¿Seguridad manda sobre el rol médico clínico?", "No; protege y coordina, no sustituye al médico", ["Sí siempre", "Sí para diagnosticar", "Sí para operar"]),
        ("Identificar a alguien en una puerta:", "Pedir identificación / motivo según protocolo de RP", ["Dejar pasar a todos", "Insultar", "Banear por preguntar"]),
        ("Buen Jefe de Seguridad:", "Calma, protocolo y comunicación", ["Solo el título", "Abusa del poder", "Desaparece en incidentes"]),
        ("Evidencias de un incidente:", "Se conservan de forma ordenada para el staff", ["Se borran siempre", "Se publican para drama", "Se falsifican"]),
        ("Apoyo a enfermería/médica en caos:", "Priorizar seguridad de la escena para que atiendan", ["Impedir toda atención", "Ignorar pedidos de ayuda", "Trollear pacientes"]),
        ("Un civil de RP grita en recepción:", "Se contiene con proporcionalidad y se reporta si hace falta", ["Se le pega sin motivo de rol", "Se ignora un peligro real de escena", "Se cierra el hospital entero siempre"]),
        ("Turnos de seguridad buscan:", "Cobertura estable de puntos clave", ["Nadie en puerta nunca", "Una sola persona sin relevo eterno a la fuerza", "Caos"]),
        ("¿Se inventan delitos solo para PK?", "No; se mantiene RP serio y justificado", ["Sí siempre", "Sí si hay aburrimiento", "Sí en anuncios"]),
        ("Coordinar con staff admin en OOC grave:", "Escalar con datos claros", ["Ocultar", "Amenazar", "Ignorar"]),
        ("Al terminar un incidente:", "Informe breve y volver a la cobertura normal", ["Abandonar el puesto sin más", "Borrar todo rastro útil", "Premiar el abuso"]),
    ]),
}
